### ISSUE TITLE
[Feature Request] CrystalOptimizer Integration

### ISSUE THREAD

**Issue by R00tB33rMan** [ItziSpyder/ClickCrystals#1]
This would not ruin the functionality and legitimacy of this mod, given it'd synchronize with another mod **only** when the CrystalOptimizer mod is identified: https://github.com/CDAGaming/CrystalOptimizer

Crystals appear to be delayed with this mod installed, so having this as a seamless integration would make my overall experience feel and be more fluid.

**Comment by ItziSpyder** [comment]
> This would not ruin the functionality and legitimacy of this mod, given it'd synchronize with another mod **only** when the CrystalOptimizer mod is identified: https://github.com/CDAGaming/CrystalOptimizer
> 
> Crystals appear to be delayed with this mod installed, so having this as a seamless integration would make my overall experience feel and be more fluid.

From personal experience, this mod works extremely well with [Marlow's Crystal Optimizer](https://www.youtube.com/watch?v=CcFT5KuQoZk). This mod simply removes the crystal client-side instead of waiting for the server to remove it for you, and actually deletes the crystal as you break it.

I would highly recommend this mod if you are experiencing issues with crystal speed.

**Comment by R00tB33rMan** [comment]
> > This would not ruin the functionality and legitimacy of this mod, given it'd synchronize with another mod **only** when the CrystalOptimizer mod is identified: https://github.com/CDAGaming/CrystalOptimizer
> > Crystals appear to be delayed with this mod installed, so having this as a seamless integration would make my overall experience feel and be more fluid.
> 
> From personal experience, this mod works extremely well with [Marlow's Crystal Optimizer](https://www.youtube.com/watch?v=CcFT5KuQoZk). This mod simply removes the crystal client-side instead of waiting for the server to remove it for you, and actually deletes the crystal as you break it.
> 
> I would highly recommend this mod if you are experiencing issues with crystal speed.

Ah! I see. Well, this GitHub link is by the same developer as Marlow’s optimizer. This is just the open source iteration of it. You’re saying it already integrates compatibility for faster crystal speeds?

**Comment by ItziSpyder** [comment]
> Ah! I see. Well, this GitHub link is by the same developer as Marlow’s optimizer. This is just the open source iteration of it. You’re saying it already integrates compatibility for faster crystal speeds?

ClickCrystals listens for certain packets sent by the client to the server, cancels it, then sends a different packet. This method should work well with the optimizer without having integrated anything.

An example would be punching an obsidian with an end crystal resulting in a right click instead. Breaking crystals would be the same, and unchanged, so in theory would not affect the optimizer's performance.

ClickCrystals:
- Manipulates user inputs.

Marlow's:
- Removes crystal entities without it being server-dependent.

**Comment by R00tB33rMan** [comment]
That makes sense! One more thing, since it'd be better to ask here: do you intend on integrating 1.19.4 support?

**Comment by ItziSpyder** [comment]
ClickCrystals was initially released for Minecraft Java version 1.19.3. However, after receiving countless requests for downgrading I eventually released a version for 1.19.2 as I was informed that most people stilled played on that version, if not, lower. I may intend to support version 1.19.4 if in demand, but will not do so without, for I see no reason to play on that version right before [Minecraft 1.20](https://www.minecraft.net/en-us/article/try-first-minecraft-1-20-features) releases.

Note: I wasn't expecting much of an issue building the project for different Minecraft versions, but Mojang has recently changed the way gui widgets work, making it difficult to hop between versions. I've been receiving reports of the gui widgets being unresponsive to user inputs on Minecraft version 1.19.2.

**Comment by R00tB33rMan** [comment]
Understandable. Appreciate the insight nonetheless!

**Comment by ItziSpyder** [comment]
Very well then! Oh, and I was saying that I'd update if in demand, turns out not long after it was! ClickCrystals is now updated to [ClickCrystal 1.19.4-0.6.5](https://modrinth.com/mod/clickcrystals/version/1.19.4-0.6.5), and the issue for unresponsive buttons is now [patched](https://modrinth.com/mod/clickcrystals/version/1.19.2-0.6.5).

**Comment by R00tB33rMan** [comment]
Mod works as intended on 1.19.4. Really appreciate this!
