### ISSUE TITLE
1.20 it's been a month

### ISSUE THREAD

**Issue by ayaanibrahimtutla** [ItziSpyder/ClickCrystals#13]
1.20 has been released and no updates. You have literally made another project 2 days back. So just update the `gradle.properties file` and test. If it works just update it please.

**Comment by ayaanibrahimtutla** [comment]
Sorry I didn't know you were at vacation. Even then PLEASE make it 1.20 I'm telling you you will get al lot of downloads the reason most of my friends are not installing this is because it's not 1.20

**Comment by ItziSpyder** [comment]
Sorry for late reply, I was on a vacation, and took an extra few days to deal with jet lag. 
Alright with that said, yes I will be releasing 1.20-0.8.6 soon!
Thanks for checking in on the project!

**Comment by ItziSpyder** [comment]
ClickCrystals has updated.
