### ISSUE TITLE
Can't Launch ClickCrystals

### ISSUE THREAD

**Issue by Menalume** [ItziSpyder/ClickCrystals#17]
Fabric loader and fabric api are all up to date
Game crashes every time you try to launch it
Exit Code is 255

**Comment by ItziSpyder** [comment]
Sure I'll take a look at it, please send the crash log to either here or the ClickCrystals discord server. Thank you for reporting this to me.

**Comment by Menalume** [comment]
https://github.com/ItziSpyder/ClickCrystals/assets/141660693/5e231dde-13bf-4217-8f78-24ea1a4acdb3

**Comment by ItziSpyder** [comment]
> https://github.com/ItziSpyder/ClickCrystals/assets/141660693/5e231dde-13bf-4217-8f78-24ea1a4acdb3

I am sorry but sending a screenshot of the game crashed screen doesn't tell me much information. Can you please check crash logs? It should be under `.minecraft/crash_reports`.

**Comment by ItziSpyder** [comment]
closed as no reply in over a month
