### ISSUE TITLE
Can there be 1.19.4 with all of the features? ( Obi search/crystal sercrch ) you know what I mean

### ISSUE THREAD

**Issue by Dopeyboisback** [ItziSpyder/ClickCrystals#2]
I am saying this because I am in an amp with my friends and my teammate can't cpvp for his life and it's a 1.19.4 server. And everyone else can cpvp. I've tried training him but he is just not reachable. So if it doesn't bother you, can you make 1.19.4 comparability?

**Comment by ItziSpyder** [comment]
Sure thing! I'll get to it when I'm available.

**Comment by Dopeyboisback** [comment]
Thanks Mutch appreciated. You will help him alot

**Comment by ItziSpyder** [comment]
No problem! The mod is now updated to [ClickCrystals 1.19.4-0.6.5](https://modrinth.com/mod/clickcrystals/version/1.19.4-0.6.5), I hope you and your friend get to enjoy the fun experiences of cpvp! Thank your so much for your stars and support! Have a nice day/night.

**Comment by Dopeyboisback** [comment]
Very helpful will tell as many people as possible about this.
