### ISSUE TITLE
Please add the features back

### ISSUE THREAD

**Issue by SeedCrackerXEnjoyer** [ItziSpyder/ClickCrystals#27]
Why would you care if people call it CW? This recent change has downgraded the overall mod. 

Oh and also the new gui gets very pixilated if you have low aspect ratio (i have that because i have low end laptop) to the point where you can't make anything out.

Thanks in advance.

**Comment by R00tB33rMan** [comment]
I generally don’t butt in on conversations that facilitate general preference but I originally enjoyed this mod prior to its update where it removed most of its CW-based modifications in attempts to consider itself a permitted mod on servers. It would be nice to see an iteration of ClickCrystals that had much of its original CW-based features for testing and debugging other users, since in environments that you are permitted and fully control, this was once a remarkably useful tool.

**Comment by I-No-oNe** [comment]
@SeedCrackerXEnjoyer, @ItziSpyder return back the old features to cc so please close ur problem

**Comment by ItziSpyder** [comment]
> I generally don’t butt in on conversations that facilitate general preference but I originally enjoyed this mod prior to its update where it removed most of its CW-based modifications in attempts to consider itself a permitted mod on servers. It would be nice to see an iteration of ClickCrystals that had much of its original CW-based features for testing and debugging other users, since in environments that you are permitted and fully control, this was once a remarkably useful tool.

Indeed I should very much add the old features back. (NoBreakDelay added back + Added CCS script)
CCS script is a fast and easy Custom Module Maker.

meanwhile CCS being CCS:
```
module create attack-on-obsidian
description Totally not straight up hax


on tick if holding :end_crystal if_not target_block :obsidian turn_to nearest_block :obsidian

// previous explosion blasted you backwards
on tick if holding :end_crystal if target_block :obsidian input forward

on tick if holding :end_crystal if target_block :obsidian input use

// prevent the next explosion from blasting you too far away
on tick if holding :end_crystal if target_entity :end_crystal input forward

on tick if holding :end_crystal if target_entity :end_crystal input attack
```

**Comment by ItziSpyder** [comment]
Need help with CCS module scripting? [Check out CCS Wiki!](https://github.com/ItziSpyder/ClickCrystals/wiki/Using-ClickCrystalsScript)
