### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by OPChickenTamali** [ItziSpyder/ClickCrystals#28]
I recently download Click Crystals and opened it up in Feather Client. When I get into the game, none of the shortcuts or anything work. It doesn't seem to be working or I might not be downloading the correct thing. Please let me know.

**Comment by ItziSpyder** [comment]
I've have written solutions for these type of situations, please refer to https://itzispyder.github.io/clickcrystals/wiki

**Comment by ItziSpyder** [comment]
If you are up to date with the latest versions, a command `,keybinds` should also be accessible to you, which opens up the client settings screen for you. You could also edit ClickCrystals keybinds through there and press the keybind in game.

**Comment by OPChickenTamali** [comment]
Thank you!

**Comment by ItziSpyder** [comment]
No problem! Issue will now be resolved as closed.
