### ISSUE TITLE
does not work on pojavlauncher

### ISSUE THREAD

**Issue by jdisi2k29** [ItziSpyder/ClickCrystals#31]
When the new mod interface came out, the mod started working very badly on pojavlauncher, crashing, lagging, and so on, from versions starting from 0.9.7 and higher, it stopped running at all, giving errors, please fix it

**Comment by ItziSpyder** [comment]
This has been happening a lot lately, and the lags and crashes are caused by Discord RPC that have been added around that time.
ClickCrystals uses a java discord presence API provided by [MinnDevelopment](https://github.com/MinnDevelopment/java-discord-rpc), and I have reason to believe it was not meant for MacOS and phones after compilation. This sparks a dilemma: should I remove Discord RPC entirely, or just expect everyone to play Java Edition normally?

**Comment by jdisi2k29** [comment]
> This has been happening a lot lately, and the lags and crashes are caused by Discord RPC that have been added around that time. ClickCrystals uses a java discord presence API provided by [MinnDevelopment](https://github.com/MinnDevelopment/java-discord-rpc), and I have reason to believe it was not meant for MacOS and phones after compilation. This sparks a dilemma: should I remove Discord RPC entirely, or just expect everyone to play Java Edition normally?

I think people could play without Discord RPC, or at least release a version without RPC, I will be glad of your decision!

**Comment by jdisi2k29** [comment]
> This has been happening a lot lately, and the lags and crashes are caused by Discord RPC that have been added around that time. ClickCrystals uses a java discord presence API provided by [MinnDevelopment](https://github.com/MinnDevelopment/java-discord-rpc), and I have reason to believe it was not meant for MacOS and phones after compilation. This sparks a dilemma: should I remove Discord RPC entirely, or just expect everyone to play Java Edition normally?

I think people could play without Discord RPC, or at least release a version without RPC, I will be glad of your decision!

**Comment by jdisi2k29** [comment]
> This has been happening a lot lately, and the lags and crashes are caused by Discord RPC that have been added around that time. ClickCrystals uses a java discord presence API provided by [MinnDevelopment](https://github.com/MinnDevelopment/java-discord-rpc), and I have reason to believe it was not meant for MacOS and phones after compilation. This sparks a dilemma: should I remove Discord RPC entirely, or just expect everyone to play Java Edition normally?

I think people could play without Discord RPC, or at least release a version without RPC, I will be glad of your decision!

**Comment by I-No-oNe** [comment]
> # Important message
> Recently several users had crash problems with ClickCrystals, the problem was caused by the `Discord RPC module`, therefore I made a special version for ClickCrystals without the `Discord RPC module`.
> 
> ## Links:
> - Download link-https://github.com/I-No-oNe/ClickCrystals-without-Discord-RPC/releases
> - Open source link-https://github.com/I-No-oNe/ClickCrystals-without-Discord-RPC
> - Link to the original version made by ImproperIssues-https://github.com/ItziSpyder/ClickCrystals
> 
> ## Important clarification:
> - This version is mainly intended for pojav and macos users
> - I-No-oNe will try to adapt this version according to the original version as much as possible
> 
> ### Tysm for downloading and happy cpvping!

**Comment by I-No-oNe** [comment]
@jdisi2k29

**Comment by jdisi2k29** [comment]
> @jdisi2k29

YOU ARE THE BEST, THANK YOU

**Comment by jdisi2k29** [comment]
In version 1.1.0, there was an attempt to fix the crash in pojavlauncher due to rpc, but it was unsuccessful, the crash is still the same

**Comment by I-No-oNe** [comment]
Do u use any other mods?

**Comment by I-No-oNe** [comment]
I have a tester who check and it worked for him

**Comment by jdisi2k29** [comment]
> I have a tester who check and it worked for him

I have no additional mods, only fabric api and clickcrystal, please tell me where you downloaded pojavlauncher from? from the github or in the play store?

**Comment by I-No-oNe** [comment]
> > I have a tester who check and it worked for him
> 
> I have no additional mods, only fabric api and clickcrystal, please tell me where you downloaded pojavlauncher from? from the github or in the play store?

As much as I know u need to download pojav from **Google play**, u also need to download the right fabric loader version(just please check on Google), also please check u download the right version of the **fabric api**.
also, in the next week, maybe I will ***update*** this version to be synced with the original version

**Comment by jdisi2k29** [comment]
> > > I have a tester who check and it worked for him
> > 
> > 
> > I have no additional mods, only fabric api and clickcrystal, please tell me where you downloaded pojavlauncher from? from the github or in the play store?
> 
> As much as I know u need to download pojav from **Google play**, u also need to download the right fabric loader version(just please check on Google), also please check u download the right version of the **fabric api**. also, in the next week, maybe I will _**update**_ this version to be synced with the original version

I checked everything, still the same error, I have the latest version of API fabric for 1.20.1

**Comment by I-No-oNe** [comment]
hmmmm

**Comment by I-No-oNe** [comment]
### Crash log?

**Comment by I-No-oNe** [comment]
@jdisi2k29

**Comment by jdisi2k29** [comment]
> @jdisi2k29
https://www.mediafire.com/file/846b3vf5sn4hl4z/latestlog.txt/file

**Comment by ItziSpyder** [comment]
y'all chillax fr I be getting these emails like crazy. just use the discord

**Comment by I-No-oNe** [comment]
@jdisi2k29, please contact me on Discord (i_no_am)
