### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SeedCrackerXEnjoyer** [ItziSpyder/ClickCrystals#32]
Make the hover totem in guicursor module programable. What I mean by programmable is to be able to tell it what order of totems to use. It looks really obvious when an admin does /invsee and sees that your totems are neatly being used from left to right on each row.

**Comment by I-No-oNe** [comment]
@SeedCrackerXEnjoyer Please suggest this on the discord server, this page is for issues.

**Comment by ayaanibrahimtutla** [comment]
@ItziSpyder  please close this

**Comment by ItziSpyder** [comment]
Closing this issue as the hover cursor is being queued for next render draw call. Currently, the method I'm using is not efficient if done randomly. Render calls draw in order from left to right, then top to bottom.
