### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by MistaMark** [ItziSpyder/ClickCrystals#50]
Hello, I used this old click crystal before and it was the best mod I've ever had. After the update it even improved more, but it doesn't work. Like I can set everything up, but it doesn't change anything. How can I fix that?

**Comment by MistaMark** [comment]
btw I play on 1.20.2. Maybe it's because of the version?

**Comment by ItziSpyder** [comment]
You're going to have to explain more in detail. I don't know what's wrong on your side. "It doesn't work" doesn't explain anything.

**Comment by ItziSpyder** [comment]
Issue closed due to no response within 3 days.
