### ISSUE TITLE
How to edit armour hud

### ISSUE THREAD

**Issue by PoojaSagarCD99955** [ItziSpyder/ClickCrystals#51]
Tell how to edit armour hud

**Comment by ItziSpyder** [comment]
The ArmorHud extends the class "FixedHud". And as the name suggests, it is indeed a fixed HUD, meaning you cannot move it around and it's position is fixed.

If you do want to switch it to the left side, you can. Simple right click the module "Armor Hud" in the GUI and set the enum setting.

Have a nice day!
