### ISSUE TITLE
how to turn off certain things

### ISSUE THREAD

**Issue by memphydemphy** [ItziSpyder/ClickCrystals#62]
How do i turn off "click crystals staff joined" Or the click crystals loading screen. The staff thing  is really annoying and I just prefer the og loading screen

**Comment by I-No-oNe** [comment]
You can't  turn off this thing. If you don't want them, just use extrarnl mods or just don't use ClickCrystals 

> Please close this issue if you don't have any more questions

**Comment by I-No-oNe** [comment]
@ItziSpyder I think you can close this issue
