### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kittenvr** [ItziSpyder/ClickCrystals#67]
what you use for their ui, did you make it yourself?

**Comment by ItziSpyder** [comment]
Yes, I made it myself

**Comment by kittenvr** [comment]
> Yes, I made it myself

can you make it so people can easily use it as a base?

**Comment by ItziSpyder** [comment]
Wdym and may I ask why?

**Comment by I-No-oNe** [comment]
@kittenvr use ImproprUi
Rendering is complicated 😢

**Comment by kittenvr** [comment]
> ImproprUi

can you send the link

**Comment by I-No-oNe** [comment]
> > ImproprUi
> 
> can you send the link

https://github.com/ItziSpyder/ImproperUI
Please close the issue
