### ISSUE TITLE
crystalautoclicker crash

### ISSUE THREAD

**Issue by davidhun0000** [ItziSpyder/ClickCrystals#7]
the crystalautoclicker is crashes the game

**Comment by ItziSpyder** [comment]
Thank you for reporting this issue, we will try to get it resolved as soon as possible. However, the team has been very busy lately and probably won't get to it within a reasonable time, we are so sorry for the inconvenience.

**Comment by ItziSpyder** [comment]
Unfortunately, we will have removed this module due to being "hacked client feature". All unfair modules and auto-clickers are now removed from the mod. You can check out this version on [Modrinth](https://modrinth.com/mod/clickcrystals).
