### ISSUE TITLE
Self Destruct Module

### ISSUE THREAD

**Issue by chikensigma99** [ItziSpyder/ClickCrystals#71]
I need it

**Comment by I-No-oNe** [comment]
Silk touch module

**Comment by chikensigma99** [comment]
it closes my game

**Comment by I-No-oNe** [comment]
That's the point

**Comment by ItziSpyder** [comment]
> That's the point

I don't think you know what self destruct means

**Comment by I-No-oNe** [comment]
> > That's the point
> 
> I don't think you know what self destruct means

oh
I don't think we need such a thing with cc

**Comment by I-No-oNe** [comment]
cause cc isn't a hack

**Comment by I-No-oNe** [comment]
@ItziSpyder close issue?

**Comment by ItziSpyder** [comment]
Issue closed due to inactivity.
